/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DataBase.DataBase;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class GUIInter extends javax.swing.JFrame {
    public String[] reic=new String[]{"id","№","Время отправления","Количество мест"};
    public String[] marsh1=new String[]{"id","№","Остановка","Время"};
    public String[] marsh=new String[]{"№","Маршрут","Продолжительность движения","Количество остановок"};
    public DefaultTableModel model,model1,model2,model3,model4,model5;
    /**
     * Creates new form GUIInter
     */
    public GUIInter(String s) {
        initComponents();
        try
        {
            DataBase.Connect();
        }
        catch(SQLException ex)
        {
            System.out.print(ex);
        }
        if(!s.equals("admin")){
            jTabbedPane1.remove(4);
            jTabbedPane1.remove(3);
        }
        model=(DefaultTableModel)jTable2.getModel();
        model1=(DefaultTableModel)jTable1.getModel();
        model2=(DefaultTableModel)jTable3.getModel();
        model3=(DefaultTableModel)jTable4.getModel();
        model4=(DefaultTableModel)jTable5.getModel();
        model5=(DefaultTableModel)jTable6.getModel();
        model.setColumnIdentifiers(reic);
        model1.setColumnIdentifiers(marsh);
        model2.setColumnIdentifiers(reic);
        model3.setColumnIdentifiers(marsh);
        model4.setColumnIdentifiers(reic);
        model5.setColumnIdentifiers(marsh1);
        Update();
        jComboBox2ItemStateChanged(null);
    }

    public void Update(){
        model.setRowCount(0);
        model4.setRowCount(0);
        model5.setRowCount(0);
        String query="select * from reic";
        ArrayList<String> result = DataBase.Select(query);
        for(int i = 0; i < result.size(); i++)
        {
            String[] string = result.get(i).split(";");
            model.addRow(string);
            model4.addRow(string);
        }
        query="select * from marsh";
        result = DataBase.Select(query);
        for(int i = 0; i < result.size(); i++)
        {
            String[] string = result.get(i).split(";");
            model5.addRow(string);
        }
        query="select distinct(ost) from marsh";
        result = DataBase.Select(query);
        for(int i = 0; i < result.size(); i++)
        {
            String[] string = result.get(i).split(";");
            jComboBox1.addItem(string[0]);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ИПС Автовокзал");
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setText(">");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Маршруты", jPanel1);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Подобрать");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1165, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Рейсы", jPanel2);

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Общая продолжительность", "Количество остановок" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jButton11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton11.setText("Сохранить");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Сортировка рейсов", jPanel3);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton3.setText("Новая строка");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton4.setText("Сохранить");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton5.setText("Удалить");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton6.setText("Редактировать");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addGap(0, 513, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Редактирование рейсов", jPanel4);

        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton7.setText("Новая строка");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton8.setText("Сохранить");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton9.setText("Удалить");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton10.setText("Редактировать");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(jTable6);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10)
                        .addGap(0, 513, Short.MAX_VALUE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Редактирование маршрута", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1177, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        if(jTable2.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this, "Выберите строку");
            return;
        }
        model1.setRowCount(0);
        String query="select * from marsh where num='"+jTable2.getValueAt(jTable2.getSelectedRow(), 1)+"'";
        ArrayList<String> result = DataBase.Select(query);
        String m="";
        int p=0,k=0;
        model1.addRow(new String[]{null});
        for(int i = 0; i < result.size(); i++)
        {   
            String[] string = result.get(i).split(";");
            m+=string[2]+';';
            p+=Integer.parseInt(string[3]);
            k++;
            jTable1.setValueAt(string[1], 0, 0);
        }
        jTable1.setValueAt(m, 0, 1);
        jTable1.setValueAt(p+" мин", 0, 2);
        jTable1.setValueAt(k, 0, 3);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        model2.setRowCount(0);
        String query="select distinct(num) from marsh where ost='"+jComboBox1.getSelectedItem()+"'";
        ArrayList<String> result = DataBase.Select(query);
        for(int i = 0; i < result.size(); i++)
        {   
            String[] string = result.get(i).split(";");
            query="select * from reic where num='"+string[0]+"' order by time asc";
            ArrayList<String> result2 = DataBase.Select(query);
            for(int j = 0; j < result2.size(); j++)
            {   
                String[] string2 = result2.get(j).split(";");
                model2.addRow(string2);
            }
        }
        for(int j=0; j<model2.getRowCount(); j++)
            for(int i=0; i<model2.getRowCount()-1; i++){
                if(Integer.parseInt(jTable3.getValueAt(i, 2).toString())>Integer.parseInt(jTable3.getValueAt(i+1, 2).toString()))
                    model2.moveRow(i, i, i+1);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
        model3.setRowCount(0);
        String query="select id,num from reic";
        ArrayList<String> result = DataBase.Select(query);
        for(int i = 0; i < result.size(); i++)
        {   
            String[] string = result.get(i).split(";");
            model3.addRow(new String[]{null});
            jTable4.setValueAt(string[0], i, 0);
            jTable4.setValueAt(string[1], i, 1);
            query="select * from marsh where num='"+string[1]+"'";
            ArrayList<String> result2 = DataBase.Select(query);
            int p=0,k=0;
            for(int j = 0; j < result2.size(); j++)
            {   
                String[] string2 = result2.get(j).split(";");
                p+=Integer.parseInt(string2[3]);
                k++;
            }
            jTable4.setValueAt(p, i, 2);
            jTable4.setValueAt(k, i, 3);
        }
        if(jComboBox2.getSelectedIndex()==0)
        {
            for(int j=0; j<model3.getRowCount(); j++)
                for(int i=0; i<model3.getRowCount()-1; i++)
                    if(Integer.parseInt(jTable4.getValueAt(i, 2).toString())>Integer.parseInt(jTable4.getValueAt(i+1, 2).toString()))
                        model3.moveRow(i, i, i+1);
        }
        else
        {
            for(int j=0; j<model3.getRowCount(); j++)
                for(int i=0; i<model3.getRowCount()-1; i++)
                    if(Integer.parseInt(jTable4.getValueAt(i, 3).toString())>Integer.parseInt(jTable4.getValueAt(i+1, 3).toString()))
                        model3.moveRow(i, i, i+1);
        }
            
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:
        try(FileWriter writer = new FileWriter("sortreices"+".txt", false))
        {
            String text="";
            for(int i=0; i<jTable4.getRowCount(); i++)
            {
                for(int j=0; j<jTable4.getColumnCount(); j++)
                     text += jTable4.getValueAt(i, j).toString()+' ';
                text+="\n";
            }
            writer.write(text);
            writer.flush();
            JOptionPane.showMessageDialog(this, "Файл сохранен!","Справка",1);
        }
        catch(IOException ex)
        {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        model4.addRow(new String[]{null});
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        model5.addRow(new String[]{null});
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        if(jTable6.getSelectedRow()==-1)
        {
            JOptionPane.showMessageDialog(this, "Выберите строку!");
            return;
        }
        for(int i=0; i<jTable6.getColumnCount(); i++)
            if(jTable6.getValueAt(jTable6.getSelectedRow(), 1)==null || jTable6.getValueAt(jTable6.getSelectedRow(), 1).toString().length()==0)
            {
                JOptionPane.showMessageDialog(this, "Заполните все поля!");
                return;
            }

        String query="insert into marsh (num,ost,time) values ('";
        for(int i=1; i<jTable6.getColumnCount()-1; i++)
            query+=jTable6.getValueAt(jTable6.getSelectedRow(), i)+"','";
        query+=jTable6.getValueAt(jTable6.getSelectedRow(), jTable6.getColumnCount()-1)+"')";

        if(DataBase.Update(query)==1)
            JOptionPane.showMessageDialog(this, "Успех!");
        else
            JOptionPane.showMessageDialog(this, "Неудачно!");

        Update();
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        if(jTable5.getSelectedRow()==-1)
        {
            JOptionPane.showMessageDialog(this, "Выберите строку!");
            return;
        }
        String query="delete from reic where id='"+jTable5.getValueAt(jTable5.getSelectedRow(), 0)+"'";
        
        if(DataBase.Update(query)==1)
            JOptionPane.showMessageDialog(this, "Успех!");
        else
            JOptionPane.showMessageDialog(this, "Неудачно!");
        Update();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        if(jTable5.getSelectedRow()==-1)
        {
            JOptionPane.showMessageDialog(this, "Выберите строку!");
            return;
        }
        String query="update reic set num='"+jTable5.getValueAt(jTable5.getSelectedRow(), 1)+"', time='"+jTable5.getValueAt(jTable5.getSelectedRow(), 2)+"', kol='"+jTable5.getValueAt(jTable5.getSelectedRow(), 3)+"' where id='"+jTable5.getValueAt(jTable5.getSelectedRow(), 0)+"'";

        if(DataBase.Update(query)==1)
            JOptionPane.showMessageDialog(this, "Успешно!");
        else
            JOptionPane.showMessageDialog(this, "Неудачно!");
        Update();
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        if(jTable5.getSelectedRow()==-1)
        {
            JOptionPane.showMessageDialog(this, "Выберите строку!");
            return;
        }
        for(int i=0; i<jTable5.getColumnCount(); i++)
            if(jTable5.getValueAt(jTable5.getSelectedRow(), 1)==null || jTable5.getValueAt(jTable5.getSelectedRow(), 1).toString().length()==0)
            {
                JOptionPane.showMessageDialog(this, "Заполните все поля!");
                return;
            }

        String query="insert into reic (num,time,kol) values ('";
        for(int i=1; i<jTable5.getColumnCount()-1; i++)
            query+=jTable5.getValueAt(jTable5.getSelectedRow(), i)+"','";
        query+=jTable5.getValueAt(jTable5.getSelectedRow(), jTable5.getColumnCount()-1)+"')";

        if(DataBase.Update(query)==1)
            JOptionPane.showMessageDialog(this, "Успех!");
        else
            JOptionPane.showMessageDialog(this, "Неудачно!");

        Update();
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        if(jTable6.getSelectedRow()==-1)
        {
            JOptionPane.showMessageDialog(this, "Выберите строку!");
            return;
        }
        String query="delete from marsh where id='"+jTable6.getValueAt(jTable6.getSelectedRow(), 0)+"'";
        
        if(DataBase.Update(query)==1)
            JOptionPane.showMessageDialog(this, "Успех!");
        else
            JOptionPane.showMessageDialog(this, "Неудачно!");
        Update();
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:
        if(jTable6.getSelectedRow()==-1)
        {
            JOptionPane.showMessageDialog(this, "Выберите строку!");
            return;
        }
        String query="update marsh set num='"+jTable6.getValueAt(jTable6.getSelectedRow(), 1)+"', ost='"+jTable6.getValueAt(jTable6.getSelectedRow(), 2)+"', time='"+jTable6.getValueAt(jTable6.getSelectedRow(), 3)+"' where id='"+jTable6.getValueAt(jTable6.getSelectedRow(), 0)+"'";

        if(DataBase.Update(query)==1)
            JOptionPane.showMessageDialog(this, "Успешно!");
        else
            JOptionPane.showMessageDialog(this, "Неудачно!");
        Update();
    }//GEN-LAST:event_jButton10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIInter(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    // End of variables declaration//GEN-END:variables
}
